# Usa a imagem oficial do Node.js com versão 18 LTS
FROM node:18

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos de dependência do projeto
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto para o contêiner
COPY . .

# Expõe a porta usada pela aplicação
EXPOSE 5173

# Comando para rodar o frontend em ambiente de desenvolvimento
CMD ["npm", "run", "dev"]
