version: "3.9"

services:
  frontend:
    build:
      context: .  # Aponta para o diretório raiz (onde está o package.json e o código do frontend)
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - app_network

networks:
  app_network:
    name: app_network
